references:
  restore: &restore
    restore_cache:
      keys:
        - v1-app-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

  resolve: &resolve
    run:
      name: DL all dependencies
      command: ./gradlew resolveDependencies

  save_cache: &save
    save_cache:
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
      key: v1-app-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - *restore
      - *resolve
      - *save

      - run:
          name: ktlint and verify plugin
          command: ./gradlew ktlintCheck verifyPlugin --no-daemon --max-workers 2

      - run:
          name: test
          command: ./gradlew test jacocoTestReport --no-daemon --max-workers 2

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/test-results

      - store_artifacts:
          path: build/reports

      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)

  beta:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - *restore
      - *resolve
      - *save

      - run:
          name: Release
          command: |
            ./gradlew buildPlugin publishPlugin -DVERSION=${CIRCLE_TAG#beta-} -DCHANNELS=beta

  release:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - *restore
      - *resolve
      - *save

      - run:
          name: Release
          command: |
            ./gradlew buildPlugin publishPlugin -DVERSION=${CIRCLE_TAG#release-} -DCHANNELS=default

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
      - beta:
          requires:
            - build_and_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^beta-.*/
      - release:
          requires:
            - build_and_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-.*/
